name: .NET Build and Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x
          
      - name: Restore dependencies
        run: dotnet restore
          
      - name: Build
        run: dotnet build --no-restore
          
      - name: Run Tests and Capture Output
        id: test-run
        run: |
          OUTPUT=$(dotnet test --no-build EcommerceAPI.Tests/EcommerceAPI.Tests.csproj)
          echo "$OUTPUT"
          echo "TEST_OUTPUT<<EOF" >> $GITHUB_ENV
          echo "$OUTPUT" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV
        
      - name: Determine Test Success
        run: |
          if [[ "${{ env.TEST_OUTPUT }}" == *"Passed: 10"* ]]; then
            echo "All tests passed successfully"
            exit 0
          else
            echo "Tests failed"
            exit 1
          fi

      - name: Set up environment variables
        env:
          Jwt__Key: ${{ secrets.JWT_KEY }}
        run: |
          echo "JWT_KEY is set"