name: .NET Build and Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x
          
      - name: Restore dependencies
        run: dotnet restore
          
      - name: Build
        run: dotnet build --no-restore
          
      - name: Test
        run: dotnet test --no-build EcommerceAPI.Tests/EcommerceAPI.Tests.csproj || echo "Tests completed with warnings"

      - name: Verify Tests Passed
        run: |
          if grep -q "Test Run Successful" <<< "$(dotnet test --no-build --logger:"console;verbosity=minimal" EcommerceAPI.Tests/EcommerceAPI.Tests.csproj)"; then
            echo "Tests passed successfully"
            exit 0
          else
            echo "Tests failed"
            exit 1
          fi
          
      - name: Set up environment variables
        env:
          Jwt__Key: ${{ secrets.JWT_KEY }}
        run: |
          echo "JWT_KEY is set"